import { PublicReport } from '@/observations/observationTypes'

type DemoSeed = Pick<
    PublicReport,
    | 'categorySlug'
    | 'categoryName'
    | 'observationSlug'
    | 'observationName'
    | 'latitude'
    | 'longitude'
    | 'publicLocationLabel'
    | 'comment'
    | 'timeOfDay'
    | 'confirmationCount'
    | 'disagreementCount'
    | 'confidenceBase'
> & { hoursAgo: number }

const seeds: DemoSeed[] = [
    {
        categorySlug: 'lighting',
        categoryName: 'Lighting',
        observationSlug: 'well-lit',
        observationName: 'Well-lit stretch',
        latitude: 28.6331,
        longitude: 77.2167,
        publicLocationLabel: 'Market-side pavement',
        comment: 'Shopfront lighting keeps this stretch bright after sunset.',
        timeOfDay: 'evening',
        confirmationCount: 8,
        disagreementCount: 1,
        confidenceBase: 0.9,
        hoursAgo: 2,
    },
    {
        categorySlug: 'activity',
        categoryName: 'Street activity',
        observationSlug: 'shops-open',
        observationName: 'Shops open nearby',
        latitude: 28.6324,
        longitude: 77.2181,
        publicLocationLabel: 'Inner market walkway',
        comment: 'Several shops and cafés are open.',
        timeOfDay: 'evening',
        confirmationCount: 11,
        disagreementCount: 2,
        confidenceBase: 0.91,
        hoursAgo: 3,
    },
    {
        categorySlug: 'accessibility',
        categoryName: 'Accessibility',
        observationSlug: 'step-free',
        observationName: 'Step-free pavement',
        latitude: 28.6316,
        longitude: 77.2158,
        publicLocationLabel: 'Library crossing',
        comment: 'Kerb ramp available on both sides of the crossing.',
        timeOfDay: 'afternoon',
        confirmationCount: 6,
        disagreementCount: 0,
        confidenceBase: 0.88,
        hoursAgo: 5,
    },
    {
        categorySlug: 'transport',
        categoryName: 'Transport',
        observationSlug: 'bus-stop-nearby',
        observationName: 'Bus stop nearby',
        latitude: 28.6342,
        longitude: 77.2148,
        publicLocationLabel: 'Bus stop approach',
        comment: 'Sheltered stop with regular foot traffic.',
        timeOfDay: 'morning',
        confirmationCount: 9,
        disagreementCount: 1,
        confidenceBase: 0.86,
        hoursAgo: 7,
    },
    {
        categorySlug: 'obstacles',
        categoryName: 'Obstacles',
        observationSlug: 'construction',
        observationName: 'Construction narrows pavement',
        latitude: 28.6309,
        longitude: 77.2174,
        publicLocationLabel: 'Garden-side path',
        comment: 'Temporary barrier leaves a narrow walking space.',
        timeOfDay: 'afternoon',
        confirmationCount: 4,
        disagreementCount: 1,
        confidenceBase: 0.72,
        hoursAgo: 9,
    },
    {
        categorySlug: 'lighting',
        categoryName: 'Lighting',
        observationSlug: 'dim-lighting',
        observationName: 'Dim lighting',
        latitude: 28.635,
        longitude: 77.2191,
        publicLocationLabel: 'Outer circle walkway',
        comment: 'Two lamps appear dim along this short section.',
        timeOfDay: 'night',
        confirmationCount: 5,
        disagreementCount: 2,
        confidenceBase: 0.68,
        hoursAgo: 11,
    },
    {
        categorySlug: 'activity',
        categoryName: 'Street activity',
        observationSlug: 'active-street',
        observationName: 'Active street',
        latitude: 28.6299,
        longitude: 77.2161,
        publicLocationLabel: 'Cinema-side pavement',
        comment: 'Steady pedestrian activity near the entrance.',
        timeOfDay: 'evening',
        confirmationCount: 13,
        disagreementCount: 1,
        confidenceBase: 0.94,
        hoursAgo: 13,
    },
    {
        categorySlug: 'accessibility',
        categoryName: 'Accessibility',
        observationSlug: 'uneven-pavement',
        observationName: 'Uneven pavement',
        latitude: 28.6337,
        longitude: 77.2129,
        publicLocationLabel: 'Park-edge walkway',
        comment: 'A short patch has cracked paving stones.',
        timeOfDay: 'morning',
        confirmationCount: 7,
        disagreementCount: 0,
        confidenceBase: 0.83,
        hoursAgo: 16,
    },
    {
        categorySlug: 'transport',
        categoryName: 'Transport',
        observationSlug: 'metro-nearby',
        observationName: 'Metro entrance nearby',
        latitude: 28.6311,
        longitude: 77.2198,
        publicLocationLabel: 'Station approach',
        comment: 'Signed pedestrian approach to the station entrance.',
        timeOfDay: 'afternoon',
        confirmationCount: 12,
        disagreementCount: 1,
        confidenceBase: 0.93,
        hoursAgo: 18,
    },
    {
        categorySlug: 'obstacles',
        categoryName: 'Obstacles',
        observationSlug: 'blocked-pavement',
        observationName: 'Pavement partly blocked',
        latitude: 28.6347,
        longitude: 77.2162,
        publicLocationLabel: 'Market loading area',
        comment: 'Deliveries temporarily occupy part of the pavement.',
        timeOfDay: 'morning',
        confirmationCount: 3,
        disagreementCount: 2,
        confidenceBase: 0.61,
        hoursAgo: 21,
    },
    {
        categorySlug: 'lighting',
        categoryName: 'Lighting',
        observationSlug: 'well-lit',
        observationName: 'Well-lit crossing',
        latitude: 28.632,
        longitude: 77.2119,
        publicLocationLabel: 'Park gate crossing',
        comment: 'Crossing and approach are brightly lit.',
        timeOfDay: 'night',
        confirmationCount: 10,
        disagreementCount: 0,
        confidenceBase: 0.95,
        hoursAgo: 24,
    },
    {
        categorySlug: 'activity',
        categoryName: 'Street activity',
        observationSlug: 'quiet-stretch',
        observationName: 'Quiet stretch',
        latitude: 28.636,
        longitude: 77.2144,
        publicLocationLabel: 'Office-side path',
        comment: 'Few open businesses later in the evening.',
        timeOfDay: 'night',
        confirmationCount: 6,
        disagreementCount: 1,
        confidenceBase: 0.79,
        hoursAgo: 27,
    },
    {
        categorySlug: 'accessibility',
        categoryName: 'Accessibility',
        observationSlug: 'wide-pavement',
        observationName: 'Wide, clear pavement',
        latitude: 28.6298,
        longitude: 77.2186,
        publicLocationLabel: 'Museum approach',
        comment: 'Wide path with room to pass comfortably.',
        timeOfDay: 'afternoon',
        confirmationCount: 8,
        disagreementCount: 0,
        confidenceBase: 0.9,
        hoursAgo: 31,
    },
    {
        categorySlug: 'transport',
        categoryName: 'Transport',
        observationSlug: 'auto-stand',
        observationName: 'Transport stand nearby',
        latitude: 28.6355,
        longitude: 77.2175,
        publicLocationLabel: 'Market exit',
        comment: 'Public transport options are visible from the exit.',
        timeOfDay: 'evening',
        confirmationCount: 5,
        disagreementCount: 1,
        confidenceBase: 0.76,
        hoursAgo: 35,
    },
    {
        categorySlug: 'obstacles',
        categoryName: 'Obstacles',
        observationSlug: 'waterlogging',
        observationName: 'Wet pavement patch',
        latitude: 28.6305,
        longitude: 77.2135,
        publicLocationLabel: 'Garden entrance',
        comment: 'A small wet patch narrows the usable path.',
        timeOfDay: 'morning',
        confirmationCount: 4,
        disagreementCount: 3,
        confidenceBase: 0.58,
        hoursAgo: 39,
    },
    {
        categorySlug: 'lighting',
        categoryName: 'Lighting',
        observationSlug: 'shop-lighting',
        observationName: 'Bright shopfronts',
        latitude: 28.633,
        longitude: 77.2203,
        publicLocationLabel: 'Café-side walkway',
        comment: 'Shopfronts add consistent light to the pavement.',
        timeOfDay: 'evening',
        confirmationCount: 9,
        disagreementCount: 1,
        confidenceBase: 0.87,
        hoursAgo: 44,
    },
    {
        categorySlug: 'activity',
        categoryName: 'Street activity',
        observationSlug: 'steady-footfall',
        observationName: 'Steady footfall',
        latitude: 28.6289,
        longitude: 77.2151,
        publicLocationLabel: 'Gallery-side street',
        comment: 'People are regularly walking through this area.',
        timeOfDay: 'afternoon',
        confirmationCount: 7,
        disagreementCount: 1,
        confidenceBase: 0.82,
        hoursAgo: 49,
    },
    {
        categorySlug: 'accessibility',
        categoryName: 'Accessibility',
        observationSlug: 'kerb-ramp',
        observationName: 'Kerb ramp available',
        latitude: 28.6363,
        longitude: 77.2184,
        publicLocationLabel: 'North crossing',
        comment: 'A marked kerb ramp connects both pavements.',
        timeOfDay: 'morning',
        confirmationCount: 6,
        disagreementCount: 0,
        confidenceBase: 0.89,
        hoursAgo: 53,
    },
]

export function getDemoObservations(now = new Date()): PublicReport[] {
    return seeds.map((seed, index) => {
        const observedAt = new Date(now.getTime() - seed.hoursAgo * 60 * 60 * 1000).toISOString()
        const { hoursAgo: _hoursAgo, ...report } = seed
        return {
            ...report,
            source: 'demo',
            id: `demo-observation-${index + 1}`,
            categoryId: `demo-category-${seed.categorySlug}`,
            valueId: `demo-value-${seed.observationSlug}`,
            createdAt: observedAt,
            observedAt,
            verificationStatus: 'demo',
            expiresAt: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        }
    })
}
